package com.group6.auction;
import com.group6.auction.wallet.service.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest
class WalletTransferIT {
 @Autowired JdbcTemplate jdbc;
 @Autowired WalletTransferService transfer;
 @Autowired WalletQueryService queries;
 @Autowired WalletLedger ledger;
 @Autowired com.group6.auction.wallet.admin.SystemWalletQueryService systemQueries;
 @Autowired PlatformTransactionManager manager;
 long alice,bob,product,auction,second;
 String prefix="wt_"+UUID.randomUUID().toString().substring(0,8);
 TransactionTemplate tx;
 @BeforeAll static void isolated(){if(!"true".equals(System.getenv("REGISTRATION_TEST_DATABASE")))throw new IllegalStateException("Isolated DB required");}
 @BeforeEach void setup(){
  tx=new TransactionTemplate(manager);
  tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_READ_COMMITTED);
  alice=user("a");bob=user("b");
  jdbc.update("INSERT INTO products(name,quantity) VALUES (?,1)",prefix);
  product=jdbc.queryForObject("SELECT id FROM products WHERE name=?",Long.class,prefix);
  auction=auction();second=auction();
 }
 long user(String suffix){
  String name=prefix+suffix;
  jdbc.update("INSERT INTO users(username,password_hash,role) VALUES (?,'test-unused-hash','USER')",name);
  long id=jdbc.queryForObject("SELECT id FROM users WHERE username=?",Long.class,name);
  jdbc.update("INSERT INTO wallets(user_id,wallet_type,available_balance,locked_balance,updated_at) VALUES (?,'USER',0,0,UTC_TIMESTAMP(6))",id);
  queries.deposit(name,1000);return id;
 }
 long auction(){
  jdbc.update("INSERT INTO auctions(product_id,created_by,auction_type,access_type,starting_price,min_bid_increment,start_time,end_time,status) VALUES (?,?,'NORMAL','PUBLIC',100,10,UTC_TIMESTAMP(6),DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 1 HOUR),'RUNNING')",product,alice);
  return jdbc.queryForObject("SELECT MAX(id) FROM auctions WHERE product_id=?",Long.class,product);
 }
 long available(long user){return jdbc.queryForObject("SELECT available_balance FROM wallets WHERE user_id=?",Long.class,user);}
 long held(long user){return jdbc.queryForObject("SELECT locked_balance FROM wallets WHERE user_id=?",Long.class,user);}
 @AfterEach void clean(){
  // Restore only credits generated by this test to the shared SYSTEM fixture.
  Long credit=jdbc.queryForObject("SELECT COALESCE(SUM(t.available_delta),0) FROM coin_transactions t JOIN wallets w ON t.wallet_id=w.id WHERE w.wallet_type='SYSTEM' AND t.auction_id IN (?,?)",Long.class,auction,second);
  jdbc.update("UPDATE wallets SET available_balance=available_balance-? WHERE wallet_type='SYSTEM'",credit);
  jdbc.update("DELETE FROM coin_transactions WHERE auction_id IN (?,?) OR wallet_id IN (SELECT id FROM wallets WHERE user_id IN (?,?))",auction,second,alice,bob);
  jdbc.update("DELETE FROM auctions WHERE product_id=?",product);jdbc.update("DELETE FROM products WHERE id=?",product);
  jdbc.update("DELETE FROM wallets WHERE user_id IN (?,?)",alice,bob);jdbc.update("DELETE FROM users WHERE id IN (?,?)",alice,bob);
 }
 @Test void holdsArePerAuctionAndLeaderReplacementRollsBackAtomically(){
  tx.executeWithoutResult(s->{transfer.lockToAmount(auction,alice,400);transfer.lockToAmount(second,alice,300);});
  tx.executeWithoutResult(s->transfer.lockToAmount(auction,alice,450));
  assertThat(available(alice)).isEqualTo(250);assertThat(held(alice)).isEqualTo(750);
  assertThatThrownBy(()->tx.executeWithoutResult(s->transfer.replaceLeader(auction,alice,bob,2000))).isInstanceOf(WalletException.class);
  assertThat(held(alice)).isEqualTo(750);
  tx.executeWithoutResult(s->transfer.replaceLeader(auction,alice,bob,500));
  assertThat(held(alice)).isEqualTo(300);assertThat(held(bob)).isEqualTo(500);
  tx.executeWithoutResult(s->{transfer.releaseAll(second,alice);transfer.releaseAll(second,alice);});
  assertThat(available(alice)).isEqualTo(1000);
 }
 @Test void systemQueriesSeeCommittedSettlementExactlyOnceAndRollbackNothing(){
  var before=new java.math.BigInteger(systemQueries.summary().totalReceivedCoin());
  tx.executeWithoutResult(s->{transfer.lockToAmount(auction,alice,500);});
  tx.executeWithoutResult(s->{transfer.settleAuction(auction,alice,500);s.setRollbackOnly();});
  assertThat(new java.math.BigInteger(systemQueries.summary().totalReceivedCoin())).isEqualTo(before);
  tx.executeWithoutResult(s->{transfer.settleAuction(auction,alice,500);jdbc.update("UPDATE auctions SET status='SOLD',winner_user_id=?,winning_price=500,finished_at=UTC_TIMESTAMP(6) WHERE id=?",alice,auction);});
  tx.executeWithoutResult(s->transfer.settleAuction(auction,alice,500));
  assertThat(new java.math.BigInteger(systemQueries.summary().totalReceivedCoin())).isEqualTo(before.add(java.math.BigInteger.valueOf(500)));
  assertThat(systemQueries.history(com.group6.auction.wallet.admin.SystemWalletFilters.parse(""+auction,"PAYMENT",null,null,20),null).items()).hasSize(1);
 }
 @Test void systemReadsDoNotExposeUncommittedPayment()throws Exception{
  var before=systemQueries.summary().totalReceivedCoin();
  tx.executeWithoutResult(s->transfer.lockToAmount(auction,alice,500));
  var written=new CountDownLatch(1);var release=new CountDownLatch(1);
  try(var executor=Executors.newSingleThreadExecutor()){
   var pending=executor.submit(()->tx.executeWithoutResult(s->{
    transfer.settleAuction(auction,alice,500);written.countDown();
    try{if(!release.await(10,TimeUnit.SECONDS))throw new IllegalStateException("Read test timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}
    s.setRollbackOnly();
   }));
   try{assertThat(written.await(10,TimeUnit.SECONDS)).isTrue();assertThat(systemQueries.summary().totalReceivedCoin()).isEqualTo(before);assertThat(systemQueries.history(com.group6.auction.wallet.admin.SystemWalletFilters.parse(""+auction,"",null,null,20),null).items()).isEmpty();}finally{release.countDown();}
   pending.get(10,TimeUnit.SECONDS);
  }
  tx.executeWithoutResult(s->{transfer.releaseAuction(auction);jdbc.update("UPDATE auctions SET status='UNSOLD',finished_at=UTC_TIMESTAMP(6) WHERE id=?",auction);});
  assertThat(systemQueries.summary().totalReceivedCoin()).isEqualTo(before);
 }
 @Test void settlementIsBalancedIdempotentAndPreservesOtherAuctions(){
  long system=jdbc.queryForObject("SELECT available_balance FROM wallets WHERE wallet_type='SYSTEM'",Long.class);
  tx.executeWithoutResult(s->{transfer.lockToAmount(auction,alice,600);transfer.lockToAmount(auction,bob,300);transfer.lockToAmount(second,alice,100);});
  tx.executeWithoutResult(s->transfer.settleAuction(auction,alice,500));
  assertThat(available(alice)).isEqualTo(400);assertThat(held(alice)).isEqualTo(100);
  assertThat(available(bob)).isEqualTo(1000);assertThat(held(bob)).isZero();
  tx.executeWithoutResult(s->transfer.settleAuction(auction,alice,500));
  assertThat(jdbc.queryForObject("SELECT available_balance FROM wallets WHERE wallet_type='SYSTEM'",Long.class)).isEqualTo(system+500);
  assertThatThrownBy(()->tx.executeWithoutResult(s->transfer.settleAuction(auction,bob,500))).isInstanceOf(WalletException.class);
  tx.executeWithoutResult(s->transfer.releaseAuction(second));
  assertThat(available(alice)).isEqualTo(500);
 }
 @Test void concurrentDepositsAndLocksCannotLoseCoin() throws Exception {
  try(var executor=Executors.newFixedThreadPool(2)){
   var a=executor.submit(()->queries.deposit(prefix+"a",100));
   var b=executor.submit(()->queries.deposit(prefix+"a",200));
   a.get(10,TimeUnit.SECONDS);b.get(10,TimeUnit.SECONDS);
   assertThat(available(alice)).isEqualTo(1300);
   Callable<Boolean> lock=()->{try {tx.executeWithoutResult(s->transfer.lockToAmount(auction,alice,900));return true;}catch(WalletException ex){return false;}};
   var one=executor.submit(lock);
   var two=executor.submit(()->{try{tx.executeWithoutResult(s->transfer.lockToAmount(second,alice,900));return true;}catch(WalletException ex){return false;}});
   assertThat(List.of(one.get(10,TimeUnit.SECONDS),two.get(10,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);
   assertThat(available(alice)).isEqualTo(400);assertThat(held(alice)).isEqualTo(900);
  }
 }
 @Test void detectsInconsistentLegacyHoldsAndRequiresOuterTransaction(){
  assertThatThrownBy(()->transfer.lockToAmount(auction,alice,10)).isInstanceOf(org.springframework.transaction.IllegalTransactionStateException.class);
  assertThatThrownBy(()->new TransactionTemplate(manager).executeWithoutResult(s->transfer.lockToAmount(auction,alice,10)))
   .isInstanceOf(org.springframework.transaction.IllegalTransactionStateException.class);
  jdbc.update("UPDATE wallets SET locked_balance=99 WHERE user_id=?",alice);
  assertThatThrownBy(()->tx.executeWithoutResult(s->transfer.lockToAmount(auction,alice,100)))
    .isInstanceOf(WalletException.class).hasMessage("WALLET_LEDGER_INCONSISTENT");
 }
 @Test void outerRollbackAndOverflowLeaveBalancesAndLedgerUnchanged(){
  long count=jdbc.queryForObject("SELECT COUNT(*) FROM coin_transactions WHERE wallet_id=(SELECT id FROM wallets WHERE user_id=?)",Long.class,alice);
  assertThatThrownBy(()->tx.executeWithoutResult(s->{queries.deposit(prefix+"a",100);throw new IllegalStateException("fail");})).isInstanceOf(IllegalStateException.class);
  assertThat(available(alice)).isEqualTo(1000);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM coin_transactions WHERE wallet_id=(SELECT id FROM wallets WHERE user_id=?)",Long.class,alice)).isEqualTo(count);
  assertThatThrownBy(()->queries.deposit(prefix+"a",Long.MAX_VALUE)).isInstanceOf(WalletException.class);
  assertThat(available(alice)).isEqualTo(1000);
 }
 @Test void failedLedgerInsertRollsBackBalanceUpdate(){
  long id=jdbc.queryForObject("SELECT id FROM wallets WHERE user_id=?",Long.class,alice);
  assertThatThrownBy(()->tx.executeWithoutResult(s->ledger.change(ledger.lock(id),Long.MAX_VALUE,"LOCK",-100,100)))
   .isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
  assertThat(available(alice)).isEqualTo(1000);
  assertThat(held(alice)).isZero();
 }
}
